### ISSUE TITLE
question on the reason for doing this

### ISSUE THREAD

**Issue by OliverLeitner** [kevinlekiller/linux_intel_monitor_overclocking#2]
hi kevin,

i was just browsing through github and came across your nice howto here..., while the description is really good and in depth, which made me clone it, one question stays with me:

why would you overclock an intel gpu? whats your usecase there?

just curious...

**Comment by kevinlekiller** [comment]
Hi Oliver, it's about over-clocking the monitor's timings. Monitors supply information to the GPU which tells it which timings it supports, but they can use alternate timings to the ones they tell the GPU.

There are 2 reasons I wanted to do this.

First, some monitors supply bad information to the GPU, which results in improper resolution, frame rate and color range. For example, I had one LCD monitor connected through DVI which was reporting as a HDTV and the GPU was setting the color range to limited (which is the default for HDTV's) and the colors looked washed out.

Second, running the monitor outside of the specified refresh rate range. Most LCD monitors will only support 50hz or 60hz at their max resolution, most videos play at ~24 or 25fps, by running a 60hz monitor at 48 or 72fps, we can get a 24fps video to match more closely the monitor.

In my case it's mostly the second part, with mpv-player I have a script which sets the monitor's refresh rate based on the video's FPS, [mpv has a setting](https://mpv.io/manual/master/#options-video-sync) which will adjust the video/audio speed to match the monitor's speed.
